### ISSUE TITLE
Add some examples in the readme

### ISSUE THREAD

**Issue by craftzdog** [ventsislav-georgiev/inkdrop-ol#1]
Hi Ventsi,

I tried your plugin and it works great.
Since the demo screenshot is an image, could you add some examples in the readme so that people can quickly try it?

Besides, I can't get it to point to Osaka, Japan with the following parameters:

```ol
source: osm
bing:
  imagerySet: CanvasDark
size:
  fullscreen: true
view:
  center: [34.6904406, 135.5350124]
  zoom: 4
```

https://www.google.com/maps/place/%E5%8D%81%E4%B8%89%E9%A7%85/@34.6904406,135.5350124,12.03z/data=!4m5!3m4!1s0x6000e5d201ff48ef:0x20ed63b5efed9710!8m2!3d34.7202216!4d135.4820681?authuser=1

I copied the latitude and longitude from Google Maps.
Thanks for the help!

**Comment by ventsislav-georgiev** [comment]
@craftzdog Thanks for the feedback. The default projection of OpenLayers is EPSG:3857 and for these coordinates (in reverse order)to work the projection needs to be EPSG:4326. I've released v0.5.0 with changed default projection and reversed the center coordinates order, so that the center can be used by simply copy pasting coordinates from Google Maps.

In addition, updated the readme with this example and made the [defaults.yml](https://github.com/ventsislav-georgiev/inkdrop-ol/blob/main/lib/defaults.yml) link more visible since all the available options can be quickly copied from there to try.

**Comment by craftzdog** [comment]
Thanks! It worked :D

**Comment by ventsislav-georgiev** [comment]
@craftzdog Changing the base projection broke the map aspect ratio and the tiles were stretched. Updated again with default to be EPSG:3857, and I am doing a transformation of the input coordinates from the EPSG:4326 to EPSG:3857. Works with the same config but the map looks beautiful once again. It shouldn't have looked the way you saw it when testing. 😃

**Comment by craftzdog** [comment]
Wow fast update! Works like a charm 👍 
<img width="793" alt="Screen Shot 2020-11-09 at 20 11 13" src="https://user-images.githubusercontent.com/1332805/98534406-c7bfbc80-22c7-11eb-9eac-28b977702b4b.png">
